# Generated by Django 4.2.5 on 2023-09-06 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_todolist'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='todo_app.todolist'),
        ),
    ]
