# Generated by Django 4.2.5 on 2023-09-06 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0003_todoitem_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='completed',
        ),
        migrations.AddField(
            model_name='todoitem',
            name='due_date',
            field=models.DateField(null=True),
        ),
    ]
